list=[1,2,5,7]
print(len(list))
list.append(4)
print(list)
list.sort()
print(list)
list.sort(reverse=True)
print(list)
list.insert(2,10)
print(list)
print(len(list))
list1=["b","c","a","e","d","j"]
print(sorted(list1))
list1.remove("c")
print(list1)
list1.pop(2)
print(list1)
list3=[0,1,2,3,4,5,6,7,8,9]
print(list3[0:9:2])